-   Name: Wapen jezelf tegen stress en burnout
    Teacher: Geert Vermaerke
    Date: May 9
    Year: 2023
    YearStop: 
    City: Leuven (on-line)
    Country: Belgium
    Selected: 0

-   Name: Nextflow for reproducible and automated data analysis
    Teacher: Kobe Lavaerts and Kristofer Davie
    Date: March 30-31
    Year: 2023
    YearStop: 
    City: Leuven
    Country: Belgium
    Selected: 0
    
-   Name: Biobanking & GDPR
    Teacher: René Custers
    Date: January 31
    Year: 2023
    YearStop: 
    City: Leuven
    Country: Belgium
    Selected: 0

-   Name: VIB Machine Learning Workshop
    Teacher: Sven Degroeve
    Date: November 29-30
    Year: 2021
    YearStop: 
    City: Leuven (on-line)
    Country: Belgium
    Selected: 0
    
-   Name: Boost your (digital) meeting skills
    Teacher: Gunnar Michielssen
    Date: October 25
    Year: 2021
    YearStop: 
    City: Leuven (on-line)
    Country: Belgium
    Selected: 0
    
-   Name: Statistical Thinking
    Teacher:  Highwoods - Joris De Wolf
    Date: May 3-5
    Year: 2021
    YearStop: 
    City: Leuven (on-line)
    Country: Belgium
    Selected: 1

-   Name: Screencasting from A to Z
    Teacher:  LIMEL - KU Leuven
    Date: 2nd Semester
    Year: 2019
    YearStop: 
    City: Leuven
    Country: Belgium
    Selected: 1

-   Name: Science Figured Out
    Teacher: The Floor is Yours (Toon Verlinden)
    Date: June 11
    Year: 2019
    YearStop: 
    City: Leuven
    Country: Belgium
    Selected: 0

-   Name: Scientists on Stage
    Teacher: The Floor is Yours (Hans Van de Water)
    Date: March 15 & April 1
    Year: 2019
    YearStop: 
    City: Leuven/Gent
    Country: Belgium
    Selected: 1

-   Name: Enabling Innovation
    Teacher: Max Planck Innovation and Atrineo AG
    Date: November 13
    Year: 2017
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 0

-   Name: Proposal Writing
    Teacher: Brain Cusack & Babette Regierer
    Date: October 17-18
    Year: 2016
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 1

-   Name: Team Dynamics and Leadership
    Teacher: Betty Boden
    Date: May 23-24
    Year: 2016
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 1

-   Name: Fundamentals of image processing with Adobe Photoshop
    Teacher: Katja Toepfer
    Date: April 29-30
    Year: 2015
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 0

-   Name: Intercultural Communication
    Teacher: Alexia Petersen
    Date: January 20-21
    Year: 2014
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 1

-   Name: Team Dynamics
    Teacher: Betty Boden
    Date: November 11-12
    Year: 2013
    YearStop: 
    City: Potsdam-Golm
    Country: Germany
    Selected: 0

-   Name: Basic Assistant Training
    Teacher: Liesje Liagre
    Date: May 10-11
    Year: 2012
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 1

-   Name: Unix Systems for Bioinformatics
    Teacher: Lieven Sterck
    Date: 2nd Semester
    Year: 2011
    YearStop: 2012
    City: Gent
    Country: Belgium
    Selected: 0

-   Name: Creative Thinking
    Teacher: Karl Raats
    Date: April 20-22
    Year: 2011
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 0

-   Name: Project Management
    Teacher: Tom Jacobs
    Date: March 2,9,16
    Year: 2011
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 0

-   Name: Effective Oral Presentations
    Teacher: Jean-Luc Doumont
    Date: February 1,7,10,21
    Year: 2011
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 1

-   Name: Effective Writing for Life Sciences
    Teacher: Jane Fraser
    Date: October 19-20
    Year: 2010
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 0

-   Name: Ensembl Workshop
    Teacher: Bert Overduin
    Date: September 20
    Year: 2007
    YearStop: 
    City: Gent
    Country: Belgium
    Selected: 0
